server:
  context-path: /
  undertow:
    io-threads: 16
    worker-threads: 4000
    undertow.buffer-size: 2048
    undertow.buffers-per-region: 2048
    undertow.direct-buffers: true
  port: 9999

security:
  basic:
    enabled: false

spring:
  application:
    name: grace-upms-service
  profiles:
    active: dev

  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/grace_nut?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 8449cd7016677564
    password: be3a7b03d89e0b1f
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    filters: stat
    maxActive: 20
    #初始化大小
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #配置SQL监控
  filters:
    stat:
      log-slow-sql: true
      slow-sql-millis: 1000
      merge-sql: true
    wall:
      config:
      multi-statement-allow: true

  # 多数据源,读写分离
  custom:
    datasource:
      name: ds1
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.55.52.28:3306/grace_upms?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: a52c59ae91b7473fc9fb39dfb5741db2
        password: 3d6598f7b47c186725a88a9de0619514
        type: com.alibaba.druid.pool.DruidDataSource



# redis缓存
  redis:
    # 连接超时时间（毫秒）
    timeout : 2000
    # Redis数据库索引（默认为0）
    database : 1
    # Redis服务器地址
    host : 47.96.143.154
    # Redis服务器连接端口
    port : 6379
    # Redis服务器连接密码（默认为空）
    password : 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active : 4000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait : 30000
      # 连接池中的最大空闲连接
      max-idle : 1000
#      # 连接池中的最小空闲连接
#      min-idle : 0

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage:  com.eric.grace.upms.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: "Y"
    logic-not-delete-value: "N"
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

swagger:
  basepackage: com.eric.grace.upms
  developer: grace-nut 权限框架
  service:
    name: grace-upms-service
    description: grace-nut 权限框架